icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[[block]]
block = "cpu"
format = " $icon $barchart "
format_alt = " $icon $utilization "
interval = 1


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid}"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
